version: '3'
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules  # This ensures node_modules is created fresh in the container
    ports:
      - "5000:5000"
    environment:
    - CHOKIDAR_USEPOLLING=true
    - NODE_ENV=development
    - MONGO_URL=mongodb+srv://acolak9:TikiTaka10@cluster0.jk0y8ed.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    env_file:
      - ./backend/.env # Reference to your .env file
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app #Important for hot loading
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongodb 

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
