# Use the official Node.js image
FROM node:16

# Set the working directory inside the container
WORKDIR /backend

# Copy the package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Copy the rest of the application
COPY . .

# Expose the backend port (5000)
EXPOSE 5000

# Start the application using nodemon
CMD ["nodemon", "server.js"]
